/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AnimesRouteImport } from './routes/animes'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ScheduleRouteImport } from './routes/schedule'
import { Route as SeriesRouteImport } from './routes/series'
import { Route as ApiAnilistRouteImport } from './routes/api.anilist'
import { Route as ApiAnilistCoverRouteImport } from './routes/api.anilist-cover'
import { Route as ApiAnimecixRouteImport } from './routes/api.animecix'
import { Route as ApiAnizmRouteImport } from './routes/api.anizm'
import { Route as ApiDevLogRouteImport } from './routes/api.dev-log'
import { Route as ApiEmbedRouteImport } from './routes/api.embed'
import { Route as ApiTranslateRouteImport } from './routes/api.translate'
import { Route as ApiUploadRouteImport } from './routes/api.upload'
import { Route as IzleSlugRouteImport } from './routes/izle.$slug'
import { Route as SeriSlugRouteImport } from './routes/seri.$slug'
import { Route as AnimeSlugIndexRouteImport } from './routes/anime.$slug.index'
import { Route as AnimeSlugSeasonSeasonEpisodeEpisodeRouteImport } from './routes/anime.$slug.season.$season.episode.$episode'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AnimesRoute = AnimesRouteImport.update({
  id: '/animes',
  path: '/animes',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ScheduleRoute = ScheduleRouteImport.update({
  id: '/schedule',
  path: '/schedule',
  getParentRoute: () => rootRouteImport,
} as any)
const SeriesRoute = SeriesRouteImport.update({
  id: '/series',
  path: '/series',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAnilistRoute = ApiAnilistRouteImport.update({
  id: '/api/anilist',
  path: '/api/anilist',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAnilistCoverRoute = ApiAnilistCoverRouteImport.update({
  id: '/api/anilist-cover',
  path: '/api/anilist-cover',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAnimecixRoute = ApiAnimecixRouteImport.update({
  id: '/api/animecix',
  path: '/api/animecix',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAnizmRoute = ApiAnizmRouteImport.update({
  id: '/api/anizm',
  path: '/api/anizm',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDevLogRoute = ApiDevLogRouteImport.update({
  id: '/api/dev-log',
  path: '/api/dev-log',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiEmbedRoute = ApiEmbedRouteImport.update({
  id: '/api/embed',
  path: '/api/embed',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTranslateRoute = ApiTranslateRouteImport.update({
  id: '/api/translate',
  path: '/api/translate',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiUploadRoute = ApiUploadRouteImport.update({
  id: '/api/upload',
  path: '/api/upload',
  getParentRoute: () => rootRouteImport,
} as any)
const IzleSlugRoute = IzleSlugRouteImport.update({
  id: '/izle/$slug',
  path: '/izle/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const SeriSlugRoute = SeriSlugRouteImport.update({
  id: '/seri/$slug',
  path: '/seri/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AnimeSlugIndexRoute = AnimeSlugIndexRouteImport.update({
  id: '/anime/$slug/',
  path: '/anime/$slug/',
  getParentRoute: () => rootRouteImport,
} as any)
const AnimeSlugSeasonSeasonEpisodeEpisodeRoute =
  AnimeSlugSeasonSeasonEpisodeEpisodeRouteImport.update({
    id: '/anime/$slug/season/$season/episode/$episode',
    path: '/anime/$slug/season/$season/episode/$episode',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/animes': typeof AnimesRoute
  '/auth': typeof AuthRoute
  '/schedule': typeof ScheduleRoute
  '/series': typeof SeriesRoute
  '/api/anilist': typeof ApiAnilistRoute
  '/api/anilist-cover': typeof ApiAnilistCoverRoute
  '/api/animecix': typeof ApiAnimecixRoute
  '/api/anizm': typeof ApiAnizmRoute
  '/api/dev-log': typeof ApiDevLogRoute
  '/api/embed': typeof ApiEmbedRoute
  '/api/translate': typeof ApiTranslateRoute
  '/api/upload': typeof ApiUploadRoute
  '/izle/$slug': typeof IzleSlugRoute
  '/seri/$slug': typeof SeriSlugRoute
  '/anime/$slug/': typeof AnimeSlugIndexRoute
  '/anime/$slug/season/$season/episode/$episode': typeof AnimeSlugSeasonSeasonEpisodeEpisodeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/animes': typeof AnimesRoute
  '/auth': typeof AuthRoute
  '/schedule': typeof ScheduleRoute
  '/series': typeof SeriesRoute
  '/api/anilist': typeof ApiAnilistRoute
  '/api/anilist-cover': typeof ApiAnilistCoverRoute
  '/api/animecix': typeof ApiAnimecixRoute
  '/api/anizm': typeof ApiAnizmRoute
  '/api/dev-log': typeof ApiDevLogRoute
  '/api/embed': typeof ApiEmbedRoute
  '/api/translate': typeof ApiTranslateRoute
  '/api/upload': typeof ApiUploadRoute
  '/izle/$slug': typeof IzleSlugRoute
  '/seri/$slug': typeof SeriSlugRoute
  '/anime/$slug': typeof AnimeSlugIndexRoute
  '/anime/$slug/season/$season/episode/$episode': typeof AnimeSlugSeasonSeasonEpisodeEpisodeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/animes': typeof AnimesRoute
  '/auth': typeof AuthRoute
  '/schedule': typeof ScheduleRoute
  '/series': typeof SeriesRoute
  '/api/anilist': typeof ApiAnilistRoute
  '/api/anilist-cover': typeof ApiAnilistCoverRoute
  '/api/animecix': typeof ApiAnimecixRoute
  '/api/anizm': typeof ApiAnizmRoute
  '/api/dev-log': typeof ApiDevLogRoute
  '/api/embed': typeof ApiEmbedRoute
  '/api/translate': typeof ApiTranslateRoute
  '/api/upload': typeof ApiUploadRoute
  '/izle/$slug': typeof IzleSlugRoute
  '/seri/$slug': typeof SeriSlugRoute
  '/anime/$slug/': typeof AnimeSlugIndexRoute
  '/anime/$slug/season/$season/episode/$episode': typeof AnimeSlugSeasonSeasonEpisodeEpisodeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/animes'
    | '/auth'
    | '/schedule'
    | '/series'
    | '/api/anilist'
    | '/api/anilist-cover'
    | '/api/animecix'
    | '/api/anizm'
    | '/api/dev-log'
    | '/api/embed'
    | '/api/translate'
    | '/api/upload'
    | '/izle/$slug'
    | '/seri/$slug'
    | '/anime/$slug/'
    | '/anime/$slug/season/$season/episode/$episode'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/animes'
    | '/auth'
    | '/schedule'
    | '/series'
    | '/api/anilist'
    | '/api/anilist-cover'
    | '/api/animecix'
    | '/api/anizm'
    | '/api/dev-log'
    | '/api/embed'
    | '/api/translate'
    | '/api/upload'
    | '/izle/$slug'
    | '/seri/$slug'
    | '/anime/$slug'
    | '/anime/$slug/season/$season/episode/$episode'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/animes'
    | '/auth'
    | '/schedule'
    | '/series'
    | '/api/anilist'
    | '/api/anilist-cover'
    | '/api/animecix'
    | '/api/anizm'
    | '/api/dev-log'
    | '/api/embed'
    | '/api/translate'
    | '/api/upload'
    | '/izle/$slug'
    | '/seri/$slug'
    | '/anime/$slug/'
    | '/anime/$slug/season/$season/episode/$episode'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  AnimesRoute: typeof AnimesRoute
  AuthRoute: typeof AuthRoute
  ScheduleRoute: typeof ScheduleRoute
  SeriesRoute: typeof SeriesRoute
  ApiAnilistRoute: typeof ApiAnilistRoute
  ApiAnilistCoverRoute: typeof ApiAnilistCoverRoute
  ApiAnimecixRoute: typeof ApiAnimecixRoute
  ApiAnizmRoute: typeof ApiAnizmRoute
  ApiDevLogRoute: typeof ApiDevLogRoute
  ApiEmbedRoute: typeof ApiEmbedRoute
  ApiTranslateRoute: typeof ApiTranslateRoute
  ApiUploadRoute: typeof ApiUploadRoute
  IzleSlugRoute: typeof IzleSlugRoute
  SeriSlugRoute: typeof SeriSlugRoute
  AnimeSlugIndexRoute: typeof AnimeSlugIndexRoute
  AnimeSlugSeasonSeasonEpisodeEpisodeRoute: typeof AnimeSlugSeasonSeasonEpisodeEpisodeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/animes': {
      id: '/animes'
      path: '/animes'
      fullPath: '/animes'
      preLoaderRoute: typeof AnimesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/schedule': {
      id: '/schedule'
      path: '/schedule'
      fullPath: '/schedule'
      preLoaderRoute: typeof ScheduleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/series': {
      id: '/series'
      path: '/series'
      fullPath: '/series'
      preLoaderRoute: typeof SeriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/anilist': {
      id: '/api/anilist'
      path: '/api/anilist'
      fullPath: '/api/anilist'
      preLoaderRoute: typeof ApiAnilistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/anilist-cover': {
      id: '/api/anilist-cover'
      path: '/api/anilist-cover'
      fullPath: '/api/anilist-cover'
      preLoaderRoute: typeof ApiAnilistCoverRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/animecix': {
      id: '/api/animecix'
      path: '/api/animecix'
      fullPath: '/api/animecix'
      preLoaderRoute: typeof ApiAnimecixRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/anizm': {
      id: '/api/anizm'
      path: '/api/anizm'
      fullPath: '/api/anizm'
      preLoaderRoute: typeof ApiAnizmRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/dev-log': {
      id: '/api/dev-log'
      path: '/api/dev-log'
      fullPath: '/api/dev-log'
      preLoaderRoute: typeof ApiDevLogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/embed': {
      id: '/api/embed'
      path: '/api/embed'
      fullPath: '/api/embed'
      preLoaderRoute: typeof ApiEmbedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/translate': {
      id: '/api/translate'
      path: '/api/translate'
      fullPath: '/api/translate'
      preLoaderRoute: typeof ApiTranslateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/upload': {
      id: '/api/upload'
      path: '/api/upload'
      fullPath: '/api/upload'
      preLoaderRoute: typeof ApiUploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/izle/$slug': {
      id: '/izle/$slug'
      path: '/izle/$slug'
      fullPath: '/izle/$slug'
      preLoaderRoute: typeof IzleSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/seri/$slug': {
      id: '/seri/$slug'
      path: '/seri/$slug'
      fullPath: '/seri/$slug'
      preLoaderRoute: typeof SeriSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/anime/$slug/': {
      id: '/anime/$slug/'
      path: '/anime/$slug'
      fullPath: '/anime/$slug/'
      preLoaderRoute: typeof AnimeSlugIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/anime/$slug/season/$season/episode/$episode': {
      id: '/anime/$slug/season/$season/episode/$episode'
      path: '/anime/$slug/season/$season/episode/$episode'
      fullPath: '/anime/$slug/season/$season/episode/$episode'
      preLoaderRoute: typeof AnimeSlugSeasonSeasonEpisodeEpisodeRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  AnimesRoute: AnimesRoute,
  AuthRoute: AuthRoute,
  ScheduleRoute: ScheduleRoute,
  SeriesRoute: SeriesRoute,
  ApiAnilistRoute: ApiAnilistRoute,
  ApiAnilistCoverRoute: ApiAnilistCoverRoute,
  ApiAnimecixRoute: ApiAnimecixRoute,
  ApiAnizmRoute: ApiAnizmRoute,
  ApiDevLogRoute: ApiDevLogRoute,
  ApiEmbedRoute: ApiEmbedRoute,
  ApiTranslateRoute: ApiTranslateRoute,
  ApiUploadRoute: ApiUploadRoute,
  IzleSlugRoute: IzleSlugRoute,
  SeriSlugRoute: SeriSlugRoute,
  AnimeSlugIndexRoute: AnimeSlugIndexRoute,
  AnimeSlugSeasonSeasonEpisodeEpisodeRoute:
    AnimeSlugSeasonSeasonEpisodeEpisodeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
